name: IS COMPATIBLE (PNPM PANEL)
on: [pull_request]

jobs:
  compatibilitycheck:
    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: ./heywesty-pnpmtester-panel/
    steps:
      - uses: actions/checkout@v3
      # pnpm action uses the packageManager field in package.json to
      # understand which version to install.
      - uses: pnpm/action-setup@v2
        with:
          version: 8.1.1
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
          cache-dependency-path: './heywesty-pnpmtester-panel/pnpm-lock.yaml'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Build plugin
        run: pnpm run build
      - name: Compatibility check
        run: npx @grafana/levitate@latest is-compatible --path src/module.ts --target @grafana/data,@grafana/ui,@grafana/runtime
