name: NPM - Latest Grafana API compatibility check
on: [pull_request]

jobs:
  compatibilitycheck:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./npm-test-datasource/
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: './npm-test-datasource/package-lock.json'
      - name: Install dependencies
        run: npm ci
      - name: Build plugin
        run: npm run build
      - name: Compatibility check
        run: npx @grafana/levitate@latest is-compatible --path src/module.ts --target @grafana/data,@grafana/ui,@grafana/runtime
